name: Manual Trigger and Scheduling

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy target'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

  schedule:
    - cron: '0 0 * * *' 


jobs: 
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the option
        run: echo "Selected output ${{ github.event.inputs.environment}}"


