name: Secrets and Environment variables

on:
  push:
    branches: master

env: 
    name: "mithun"

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:

      - name: Echoing Sercets
        run: echo    "Account ${{ env.name }} has ${{ secrets.GITHUB_TOKEN }} as password token"
